// <auto-generated />
namespace VoTaTung_2080601351_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Role_login : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role_login));
        
        string IMigrationMetadata.Id
        {
            get { return "202303110628449_Role_login"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
